# Site settings
title: Michael's Sick New Blog Today
email: michaellefcort@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my new blog where i will provide weekly progress updates.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mlefcort
github_username:  mlefcort

# Build settings
markdown: kramdown
